const topWearForMen = [
  "Printed T-Shirts",
  "Oversized T-shirts",
  "Plain T-Shirts",
  "Full Sleeve T-Shirts",
  "Half Sleeve T-Shirts",
  "Henleys",
  "Polo T-Shirts",
  "T-shirt Combos",
  "Sweatshirts & Hoodies",
  "Jackets",
  "Sweaters",
  "Shirts",
  "Co-ord Sets",
  "KurtasVests",
  "Plus Size Topwear",
  "Customize T-shirts",
  "All Topwear",
];
const topWearForWomen = [
  "Printed T-Shirts",
  "Boyfriend T-Shirts",
  "Oversized T-shirts",
  "Plain T-Shirts",
  "Half Sleeves T-Shirts",
  "T-shirt Combos",
  "Fashion Tops",
  "Sweatshirts & Hoodies",
  "Jackets",
  "Sweaters",
  "Co-ord Sets",
  "Kurtis",
  "Shirts",
  "Plus Size Topwear",
  "Customize T-shirts",
  "All Topwear",
];
const bottomWearForMen = [
  "Joggers",
  "Jeans & Denims",
  "Pyjamas",
  "Trousers & Pants",
  "Cargos",
  "Shorts",
  "Boxers",
  "Combos",
  "Plus Size Bottomwear",
  "All Bottomwear",
];
const bottomWearForWomen = [
  "Joggers",
  "Jeans & Denims",
  "Parachute pants",
  "Cargos",
  "Pyjamas",
  "Trousers & Pants",
  "Cargos",
  "Shorts",
  "Boxer Shorts",
  "Plus Size Bottomwear",
  "All Bottomwear",
];
const winterWearForMen = [
  "Sweatshirts & Hoodies",
  "Jackets",
  "Sweaters",
  "Full Sleeve T-Shirts",
  "Joggers",
  "Plus Size",
];
const winterWearForWomen = [
  "Jackets",
  "Sweatshirts & Hoodies",
  "Sweaters",
  "Joggers",
  "Plus Size",
];
const plusSizeForMen = [
  "T-shirts",
  "Shirts",
  "Jackets",
  "Sweatshirts & Hoodies",
  "Bottomwear",
  "Jeans & Denims",
];
const plusSizeForWomen = [
  "Topwear",
  "Shirts",
  "Sweatshirts & Hoodies",
  "Jackets",
  "Bottomwear",
  "Dresses",
];
const innerWearLoungewearForMen = ["Vests", "Pyjamas", "Boxers"];
const LoungewearForWomen = ["Shorts", "Pyjamas", "Lounge wear", "Boxers"];
